Repository Sem-in-a/Semi-na-android, pull requests merged in 2023-11, with the labels that each got.

#5 feat:로그인 퍼블리싱과 유세인트 로그인 연결
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/semina/semi_na/data/remote/.gitkeep
  app/src/main/java/com/semina/semi_na/data/remote/RetrofitClient.java
  app/src/main/java/com/semina/semi_na/data/remote/RetrofitInterface.java
  app/src/main/java/com/semina/semi_na/data/remote/entity/Member.java
  app/src/main/java/com/semina/semi_na/data/remote/request/LoginRequest.java
  app/src/main/java/com/semina/semi_na/data/remote/response/LoginResponse.java
  app/src/main/java/com/semina/semi_na/view/login/LoginActivity.java
  app/src/main/java/com/semina/semi_na/view/login/OnboardingActivity.java
  app/src/main/res/drawable/button_border.xml
  app/src/main/res/drawable/edit_text_border.xml
  app/src/main/res/drawable/login_logo.xml
  app/src/main/res/drawable/logo.xml
  app/src/main/res/drawable/mipmap_logo.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  google-services.json
Labels: feat

#10 refactor:firestore migration
  app/build.gradle.kts
  app/src/main/java/com/semina/semi_na/view/login/LoginActivity.java
  app/src/main/java/com/semina/semi_na/view/login/OnboardingActivity.java
Labels: bug, refactor

#11 fix:이미 유저 정보 있을 때 => 디비에 정보저장 X
  app/src/main/java/com/semina/semi_na/view/login/LoginActivity.java
Labels: bug

#9 feat:세미나 레이아웃 작업
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/semina/semi_na/base/CreateFragment.java
  app/src/main/java/com/semina/semi_na/base/MainActivity.java
  app/src/main/java/com/semina/semi_na/view/create/.gitkeep
  app/src/main/java/com/semina/semi_na/view/create/CreateCategoryActivity.java
  app/src/main/java/com/semina/semi_na/view/create/CreateCompleteActivity.java
  app/src/main/java/com/semina/semi_na/view/create/CreateDateActivity.java
  app/src/main/java/com/semina/semi_na/view/create/CreateHobbyActivity.java
  app/src/main/java/com/semina/semi_na/view/create/CreateLocationActivity.java
  app/src/main/java/com/semina/semi_na/view/create/CreateMajorActivity.java
  app/src/main/java/com/semina/semi_na/view/create/CreateMemberCountActivity.java
  app/src/main/java/com/semina/semi_na/view/create/CreateThumbnailActivity.java
  app/src/main/java/com/semina/semi_na/view/create/CreateTitleActivity.java
  app/src/main/java/com/semina/semi_na/view/login/LoginActivity.java
  app/src/main/java/com/semina/semi_na/view/login/OnboardingActivity.java
  app/src/main/res/drawable/category_select_btn.xml
  app/src/main/res/drawable/create_success.xml
  app/src/main/res/layout/activity_create_category.xml
  app/src/main/res/layout/activity_create_complete.xml
  app/src/main/res/layout/activity_create_date.xml
  app/src/main/res/layout/activity_create_hobby.xml
  app/src/main/res/layout/activity_create_location.xml
  app/src/main/res/layout/activity_create_major.xml
  app/src/main/res/layout/activity_create_member_count.xml
  app/src/main/res/layout/activity_create_thumbnail.xml
  app/src/main/res/layout/activity_create_title.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
  gradle.properties
Labels: feat

#12 feat: 홈화면 레이아웃 작업
  app/src/main/java/com/semina/semi_na/base/HomeFragment.java
  app/src/main/java/com/semina/semi_na/view/adapter/CollegePagerAdapter.java
  app/src/main/java/com/semina/semi_na/view/home/BusinessFragment.java
  app/src/main/java/com/semina/semi_na/view/home/EconomicsFragment.java
  app/src/main/java/com/semina/semi_na/view/home/EngineeringFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HumanityFragment.java
  app/src/main/java/com/semina/semi_na/view/home/ITFragment.java
  app/src/main/java/com/semina/semi_na/view/home/LawFragment.java
  app/src/main/java/com/semina/semi_na/view/home/NaturalScienceFragment.java
  app/src/main/java/com/semina/semi_na/view/home/SocialScienceFragment.java
  app/src/main/res/drawable/business_college_icon.xml
  app/src/main/res/drawable/economics_college_icon.xml
  app/src/main/res/drawable/engineering_college_icon.xml
  app/src/main/res/drawable/humanity_college_icon.xml
  app/src/main/res/drawable/it_college_icon.xml
  app/src/main/res/drawable/law_college_icon.xml
  app/src/main/res/drawable/natural_science_college_icon.xml
  app/src/main/res/drawable/search_icon.xml
  app/src/main/res/drawable/search_view_background.xml
  app/src/main/res/drawable/social_science_college_icon.xml
  app/src/main/res/drawable/tab_background_selector.xml
  app/src/main/res/drawable/tab_selected_background.xml
  app/src/main/res/drawable/tab_unselected_background.xml
  app/src/main/res/layout/fragment_business.xml
  app/src/main/res/layout/fragment_economics.xml
  app/src/main/res/layout/fragment_engineering.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_humanity.xml
  app/src/main/res/layout/fragment_i_t.xml
  app/src/main/res/layout/fragment_law.xml
  app/src/main/res/layout/fragment_natural_science.xml
  app/src/main/res/layout/fragment_social_science.xml
  app/src/main/res/values/strings.xml
Labels: feat, design

#13 feat:세미나 레이아웃 - 카테고리 선택
  app/src/main/java/com/semina/semi_na/data/db/entity/HobbyCategory.java
  app/src/main/java/com/semina/semi_na/data/db/entity/MajorCategory.java
  app/src/main/java/com/semina/semi_na/data/db/entity/Semina.java
  app/src/main/java/com/semina/semi_na/data/db/entity/SeminaCategory.java
  app/src/main/java/com/semina/semi_na/view/create/CreateCategoryActivity.java
  app/src/main/java/com/semina/semi_na/view/create/CreateTitleActivity.java
  app/src/main/java/com/semina/semi_na/view/login/OnboardingActivity.java
  app/src/main/res/drawable/button_select_stroke.xml
  app/src/main/res/layout/activity_create_category.xml
  app/src/main/res/layout/activity_create_date.xml
  app/src/main/res/layout/activity_create_hobby.xml
  app/src/main/res/layout/activity_create_location.xml
Labels: feat, design

#15 feat: 마이페이지 퍼블리싱
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/semina/semi_na/base/MyPageFragment.java
  app/src/main/java/com/semina/semi_na/view/mypage/LogoutModal.java
  app/src/main/java/com/semina/semi_na/view/mypage/ViewDetailAppliedActivity.java
  app/src/main/java/com/semina/semi_na/view/mypage/ViewDetailHostedActivity.java
  app/src/main/res/drawable/chevron_right.xml
  app/src/main/res/drawable/edit_1.xml
  app/src/main/res/drawable/logout.xml
  app/src/main/res/drawable/logout_btn_background.xml
  app/src/main/res/drawable/no_applied_seminer.xml
  app/src/main/res/drawable/no_hosted_seminer.xml
  app/src/main/res/drawable/profile_line.xml
  app/src/main/res/drawable/profile_logo.xml
  app/src/main/res/drawable/profile_rectangle.png
  app/src/main/res/layout/activity_view_detail_applied.xml
  app/src/main/res/layout/activity_view_detail_hosted.xml
  app/src/main/res/layout/fragment_logout_modal.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
Labels: feat, design

#16 feat: 홈화면 레이아웃 작업 마무리
  app/build.gradle.kts
  app/src/main/java/com/semina/semi_na/base/HomeFragment.java
  app/src/main/java/com/semina/semi_na/base/MainActivity.java
  app/src/main/res/drawable/participant_icon.xml
  app/src/main/res/drawable/samina_exercise_image.xml
  app/src/main/res/drawable/swift_logo.png
  app/src/main/res/drawable/tab_background_selector.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_i_t.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feat, design

#21 feat: 세미나 상세 페이지 레이아웃
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/semina/semi_na/base/HomeFragment.java
  app/src/main/java/com/semina/semi_na/view/detail/SeminaDetailActivity.java
  app/src/main/java/com/semina/semi_na/view/home/ITFragment.java
  app/src/main/res/drawable/about_host.png
  app/src/main/res/drawable/dae_500.png
  app/src/main/res/drawable/han_liver_board.png
  app/src/main/res/drawable/participant_1.png
  app/src/main/res/drawable/participant_2.png
  app/src/main/res/drawable/participant_3.png
  app/src/main/res/layout/activity_semina_detail.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
Labels: feat, design

#22 feat: 세미나 신청 완료 모달 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/semina/semi_na/view/detail/SeminaDetailActivity.java
  app/src/main/res/drawable/bottom_sheet_dialog_bg.xml
  app/src/main/res/layout/activity_semina_apply_bottom_sheet_dialog.xml
  app/src/main/res/layout/activity_semina_detail.xml
  app/src/main/res/values/styles.xml
Labels: feat

#24 feat: firebase cloud messaging 구현
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/semina/semi_na/base/MainActivity.java
  app/src/main/java/com/semina/semi_na/service/FirebaseMessagingService.java
  app/src/main/java/com/semina/semi_na/service/MyFirebaseMessagingService.java
  build.gradle.kts
  google-services.json
Labels: feat

#27 fix:fcm 로직 수정 이것저것
  .idea/deploymentTargetDropDown.xml
  README.md
  app/src/main/java/com/semina/semi_na/base/MainActivity.java
  app/src/main/java/com/semina/semi_na/data/db/entity/Member.java
  app/src/main/java/com/semina/semi_na/view/create/CreateCompleteActivity.java
  app/src/main/java/com/semina/semi_na/view/login/LoginActivity.java
  app/src/main/java/com/semina/semi_na/view/login/OnboardingActivity.java
Labels: bug, refactor

#33 feat: 취미로 찾아보는 세미나 파이어베이스 연결
  app/build.gradle.kts
  app/src/main/java/com/semina/semi_na/base/HomeFragment.java
  app/src/main/java/com/semina/semi_na/data/db/entity/HobbyCategory.java
  app/src/main/java/com/semina/semi_na/data/db/entity/Location.java
  app/src/main/java/com/semina/semi_na/data/db/entity/Semina.java
  app/src/main/java/com/semina/semi_na/data/remote/RetrofitClient.java
  app/src/main/java/com/semina/semi_na/data/remote/request/LoginRequest.java
  app/src/main/java/com/semina/semi_na/data/remote/response/LoginResponse.java
  app/src/main/java/com/semina/semi_na/view/adapter/CollegeSeminarPagerAdapter.java
  app/src/main/java/com/semina/semi_na/view/adapter/HobbySeminarPagerAdapter.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyBookFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyExerciseFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyFoodFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyMusicFragment.java
  app/src/main/java/com/semina/semi_na/view/viewHolder/SeminarCardViewHolder.java
  app/src/main/res/drawable/seminar_hobby_book.xml
  app/src/main/res/drawable/seminar_hobby_exercise.xml
  app/src/main/res/drawable/seminar_hobby_food.xml
  app/src/main/res/drawable/seminar_hobby_music.xml
  app/src/main/res/drawable/tab_background_selector.xml
  app/src/main/res/layout/fragment_hobby_book.xml
  app/src/main/res/layout/fragment_hobby_exercise.xml
  app/src/main/res/layout/fragment_hobby_food.xml
  app/src/main/res/layout/fragment_hobby_music.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/seminar_card_view_item.xml
Labels: feat

#34 fix:세부카테고리 직렬화
  app/src/main/java/com/semina/semi_na/data/db/entity/Semina.java
  app/src/main/java/com/semina/semi_na/view/create/CreateHobbyActivity.java
  app/src/main/java/com/semina/semi_na/view/create/CreateMajorActivity.java
Labels: bug, refactor

#38 feat: 전공별로 찾아보는 세미나 파이어베이스 연결
  app/src/main/java/com/semina/semi_na/base/HomeFragment.java
  app/src/main/java/com/semina/semi_na/data/db/entity/MajorCategory.java
  app/src/main/java/com/semina/semi_na/view/adapter/CollegeSeminarPagerAdapter.java
  app/src/main/java/com/semina/semi_na/view/adapter/HobbySeminarPagerAdapter.java
  app/src/main/java/com/semina/semi_na/view/home/BusinessFragment.java
  app/src/main/java/com/semina/semi_na/view/home/EconomicsFragment.java
  app/src/main/java/com/semina/semi_na/view/home/EngineeringFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyBookFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyExerciseFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyFoodFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyMusicFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HumanityFragment.java
  app/src/main/java/com/semina/semi_na/view/home/ITFragment.java
  app/src/main/java/com/semina/semi_na/view/home/LawFragment.java
  app/src/main/java/com/semina/semi_na/view/home/NaturalScienceFragment.java
  app/src/main/java/com/semina/semi_na/view/home/SocialScienceFragment.java
  app/src/main/java/com/semina/semi_na/view/viewHolder/SeminarCardViewHolder.java
  app/src/main/res/layout/fragment_business.xml
  app/src/main/res/layout/fragment_economics.xml
  app/src/main/res/layout/fragment_engineering.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_humanity.xml
  app/src/main/res/layout/fragment_i_t.xml
  app/src/main/res/layout/fragment_law.xml
  app/src/main/res/layout/fragment_natural_science.xml
  app/src/main/res/layout/fragment_social_science.xml
Labels: feat

#40 feat: 세미나 카드 뷰에 세미나 개최자 정보 넣기
  app/src/main/java/com/semina/semi_na/data/db/entity/HobbyCategory.java
  app/src/main/java/com/semina/semi_na/data/db/entity/MajorCategory.java
  app/src/main/java/com/semina/semi_na/data/db/entity/Member.java
  app/src/main/java/com/semina/semi_na/data/db/entity/Semina.java
  app/src/main/java/com/semina/semi_na/data/db/entity/SeminaCategory.java
  app/src/main/java/com/semina/semi_na/view/create/CreateMajorActivity.java
  app/src/main/java/com/semina/semi_na/view/create/CreateTitleActivity.java
  app/src/main/java/com/semina/semi_na/view/viewHolder/SeminarCardViewHolder.java
Labels: feat

#44 fix: 취미별로 찾아보는 세미나인 경우 `hobbyLocation` 적용
  app/src/main/java/com/semina/semi_na/view/viewHolder/SeminarCardViewHolder.java
  app/src/main/res/layout/seminar_card_view_item.xml
Labels: refactor

#47 Fix: 세미나 카드뷰 뷰홀더 변경 및 마이페이지 리사이클러뷰 변경
  app/src/main/java/com/semina/semi_na/base/MyPageFragment.java
  app/src/main/java/com/semina/semi_na/view/adapter/SearchResultsAdapter.java
  app/src/main/java/com/semina/semi_na/view/adapter/SeminaAdapter.java
  app/src/main/java/com/semina/semi_na/view/mypage/HostedClosedFragment.java
  app/src/main/java/com/semina/semi_na/view/mypage/HostedProceedingFragment.java
  app/src/main/java/com/semina/semi_na/view/viewHolder/DetailCardViewHolder.java
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/search_card_view_item.xml
Labels: feat

#48 refactor: 홈 화면 `ViewPager` 리팩토링
  app/src/main/java/com/semina/semi_na/base/HomeFragment.java
  app/src/main/java/com/semina/semi_na/view/adapter/CollegeSeminarPagerAdapter.java
  app/src/main/java/com/semina/semi_na/view/adapter/HobbySeminarPagerAdapter.java
  app/src/main/java/com/semina/semi_na/view/adapter/SeminarFirestorePagingAdapter.java
  app/src/main/java/com/semina/semi_na/view/home/BusinessFragment.java
  app/src/main/java/com/semina/semi_na/view/home/EconomicsFragment.java
  app/src/main/java/com/semina/semi_na/view/home/EngineeringFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyBookFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyExerciseFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyFoodFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HobbyMusicFragment.java
  app/src/main/java/com/semina/semi_na/view/home/HumanityFragment.java
  app/src/main/java/com/semina/semi_na/view/home/ITFragment.java
  app/src/main/java/com/semina/semi_na/view/home/LawFragment.java
  app/src/main/java/com/semina/semi_na/view/home/NaturalScienceFragment.java
  app/src/main/java/com/semina/semi_na/view/home/SocialScienceFragment.java
  app/src/main/java/com/semina/semi_na/view/viewHolder/CollegePagerViewHolder.java
  app/src/main/java/com/semina/semi_na/view/viewHolder/HobbyPagerViewHolder.java
  app/src/main/res/layout/college_view_pager_item.xml
  app/src/main/res/layout/fragment_business.xml
  app/src/main/res/layout/fragment_economics.xml
  app/src/main/res/layout/fragment_engineering.xml
  app/src/main/res/layout/fragment_hobby_book.xml
  app/src/main/res/layout/fragment_hobby_exercise.xml
  app/src/main/res/layout/fragment_hobby_food.xml
  app/src/main/res/layout/fragment_hobby_music.xml
  app/src/main/res/layout/fragment_humanity.xml
  app/src/main/res/layout/fragment_i_t.xml
  app/src/main/res/layout/fragment_law.xml
  app/src/main/res/layout/fragment_natural_science.xml
  app/src/main/res/layout/fragment_social_science.xml
  app/src/main/res/layout/hobby_view_pager_item.xml
Labels: refactor
